name: macOS 10.15

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'gdk-pixbuf glib glib-networking gobject-introspection pkg-config jq' }}
 
on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  # macOS tasks
  build-mac-catalina-swift-latest:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.3'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW

      - name: Checkout SwiftGdkPixbuf
        uses: actions/checkout@v2
        with:
          path: SwiftGdkPixbuf

      - name: Build Swift Wrappers
        run: |
          cd SwiftGdkPixbuf
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftGdkPixbuf
        run: |
          cd SwiftGdkPixbuf
          swift build `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Test SwiftGdkPixbuf
        run: |
          cd SwiftGdkPixbuf
          swift test `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Remove unneeded files and archive artefacts
        run: | 
          cd SwiftGdkPixbuf
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artefact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artefact-catalina
          path: |
            SwiftGdkPixbuf/
          retention-days: 1
