name: Ubuntu 20.04

# Dependencies of this package
env:
  UBUNTU_APT: ${{ 'libgdk-pixbuf2.0-dev gir1.2-gdkpixbuf-2.0  libglib2.0-dev glib-networking gobject-introspection libgirepository1.0-dev libxml2-dev jq' }}

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  # Ubuntu 20.04 tasks
  build-ubuntu-20_04-swift-latest:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Swift version to confirm
        run: swift --version
      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout SwiftGdkPixbuf
        uses: actions/checkout@v2
        with:
          path: SwiftGdkPixbuf

      - name: Build Swift Wrappers
        run: |
          cd SwiftGdkPixbuf
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftGdkPixbuf
        run: |
          cd SwiftGdkPixbuf
          swift build
          cd ..

      - name: Test SwiftGdkPixbuf
        run: |
          cd SwiftGdkPixbuf
          swift test
          cd ..

      - name: Remove unneeded files and archive artefacts
        run: | 
          cd SwiftGdkPixbuf
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artefact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artefact-20.04-5.3
          path: |
            SwiftGdkPixbuf/
          retention-days: 1
